version: '3.1'
services:
  db:
    image: postgres:15-bookworm
    restart: always
    environment:
      POSTGRES_USER: takeoutapp
      POSTGRES_PASSWORD: takeoutapp
      POSTGRES_DB: takeout_app_development
    volumes:
      - 'postgres15:/var/lib/postgresql/data'
    ports:
      - '127.0.0.1::5432'
volumes:
  postgres15: {}
