on:
  push:
    branches:
      - kaigionrails

jobs:
  build:
    runs-on: ubuntu-latest
    if: "${{ github.repository == 'kaigionrails/sponsor-app' }}"
    permissions:
      id-token: write
      contents: read
    outputs:
      image-tag: "${{ steps.login-ecr-usw2.outputs.registry }}/sponsor-app:${{ github.sha }}"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          aws-region: us-west-2
          role-skip-session-tagging: false
          role-to-assume: "arn:aws:iam::861452569180:role/GhaDockerPushToEcr"
      - id: login-ecr-usw2
        uses: aws-actions/amazon-ecr-login@19d944daaa35f0fa1d3f7f8af1d3f2e5de25c5b7 # v2.1.4
      - id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: "${{ steps.login-ecr-usw2.outputs.registry }}/sponsor-app"
          tags: |
            type=sha,format=long,prefix=
            type=raw,value=latest
      - uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: "."
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          # prevent manifest from being pushed instead of image on the specified tags for Lambda
          provenance: false
          sbom: false

  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "deploy"
      cancel-in-progress: false
    environment:
      name: production
      url: https://sponsorships.kaigionrails.org
    needs: ["build"]
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-west-2
      IMAGE_URI: ${{ needs.build.outputs.image-tag }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          aws-region: us-west-2
          role-skip-session-tagging: false
          role-to-assume: "arn:aws:iam::861452569180:role/SponsorAppDeployer"
      - run: 'aws lambda update-function-code --function-name sponsor-app-runner-production --image-uri "$IMAGE_URI" && aws lambda wait function-updated --function-name sponsor-app-runner-production'
      - run: 'bundle exec ./deploy/lambrunner.rb sponsor-app-runner-production bundle exec rake db:migrate'
      - run: 'aws lambda update-function-code --function-name sponsor-app-lambdakiq-production --image-uri "$IMAGE_URI" && aws lambda wait function-updated --function-name sponsor-app-lambdakiq-production'
      - run: 'aws lambda update-function-code --function-name sponsor-app-web-production --image-uri "$IMAGE_URI" && aws lambda wait function-updated --function-name sponsor-app-web-production'

  # TODO: DRY
  staging-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "staging-deploy"
      cancel-in-progress: false
    environment:
      name: staging
      url: https://sponsorships-staging.kaigionrails.org
    needs: ["build"]
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-west-2
      IMAGE_URI: ${{ needs.build.outputs.image-tag }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          aws-region: us-west-2
          role-skip-session-tagging: false
          role-to-assume: "arn:aws:iam::861452569180:role/SponsorAppDeployer"
      - run: 'aws lambda update-function-code --function-name sponsor-app-runner-staging --image-uri "$IMAGE_URI" && aws lambda wait function-updated --function-name sponsor-app-runner-staging'
      - run: 'bundle exec ./deploy/lambrunner.rb sponsor-app-runner-staging bundle exec rake db:migrate'
      - run: 'aws lambda update-function-code --function-name sponsor-app-lambdakiq-staging --image-uri "$IMAGE_URI" && aws lambda wait function-updated --function-name sponsor-app-lambdakiq-staging'
      - run: 'aws lambda update-function-code --function-name sponsor-app-web-staging --image-uri "$IMAGE_URI" && aws lambda wait function-updated --function-name sponsor-app-web-staging'
